
POST https://cleanslate-gamma.vercel.app/auth/signup
Content-Type: application/json

{
    "name":"hima",
    "email":"hima@gmail.com",
    "password":"hima@15",
    "cpassword":"hima@15"
}


###
POST https://cleanslate-gamma.vercel.app/auth/login
Content-Type: application/json

{
    "email":"ganesh@gmail.com",
    "password":"comrade.2003"
}